run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - tmp
    - vendor

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 15
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - typecheck
    - gocritic
    - goconst
    - gocyclo
    - dupl
    - funlen
    - gocognit
    - lll
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocognit
        - funlen
        - gocyclo
        - dupl
  max-issues-per-linter: 0
  max-same-issues: 0

